version: "3.7"

services:
  db:
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=db
    ports:
      - 27017:27017
    volumes:
      - ./dbdata:/data/db